name: anitcorona
description: A new Flutter application.

publish_to: 'none'

version: 0.60.60+4

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
#  flutter_blue: ^0.7.2
  path_provider: ^2.0.1
#  flutter_bluetooth_serial: ^0.2.2
  google_sign_in: ^5.0.0
  firebase_auth: ^1.0.0
  device_info: ^2.0.0
  shared_preferences: ^2.0.3
  geolocator: ^7.0.1
#  nearby_connections: ^3.0.0-nullsafety.0
  flutter_nearby_connections: ^1.0.11
  fl_chart: ^0.20.1
  http: ^0.13.0
  html: ^0.15.0
  sqflite: ^2.0.0+1
  intl: ^0.17.0
  url_launcher: ^6.0.2
  salomon_bottom_bar: ^3.0.0
#  fancy_on_boarding: ^1.7.0
#  eva_icons_flutter: ^2.0.0
  flutter_launcher_icons: ^0.9.0
  firebase_core: ^1.0.0
  flutter_local_notifications: ^5.0.0-nullsafety.0
  firebase_database: ^7.0.0-dev.2
  firebase_messaging: ^10.0.0
  google_fonts: ^2.0.0
  flutter_spinkit: ^5.0.0
  rounded_loading_button: ^2.0.4
  flutter_ringtone_player: ^3.0.0
  awesome_notifications: ^0.0.6+5
  flutter_background_service: ^0.1.4
  adaptive_dialog: ^0.10.0+5
  easy_dynamic_theme: ^2.2.0
  google_maps_flutter: ^2.0.6
  flutter_polyline_points: ^1.0.0
  cloud_firestore: ^2.2.0
#  charts_flutter: ^0.10.0
#  location: ^4.1.1
#  background_fetch: ^0.7.2

#dev_dependencies:
#  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images.png"
flutter:
  uses-material-design: true
  assets:
      - assets/
      - assets/icons/
      - assets/psd/
flutter_intl:
  main_locale: en
  enabled: true
