import 'package:flutter/material.dart';
const appBarColor = Color.fromRGBO(51, 102, 255, 1);
const kTextColor = Color(0xFF1E2432);
const kTextMediumColor = Color(0xFF53627C);
const kTextLightColor = Color(0xFFACB1C0);
const kPrimaryColor = Color(0xFF0D8E53);
const kBackgroundColor = Color(0xFFFCFCFC);
const kInactiveChartColor = Color(0xFFEAECEF);
const GbackgroundStatutColor=Color.fromRGBO(16, 132, 146, .99);
Color primary = Colors.blue.shade800;
const  red = Colors.red;
const Color white = Colors.white;
const Color black = Colors.black;
const Color grey = Colors.grey;
const Color green = Colors.green;
